### ISSUE TITLE
Hulu.com

### ISSUE THREAD

**Issue by davidhedlund** [chatziko/location-guard#19]
I could not hide my location with Firefox add-on Location Guard to browse [Hulu](http://www.hulu.com/), they still detected my country.

https://github.com/reek/anti-adblock-killer/issues/1561

**Comment by davidhedlund** [comment]
mylabel:invalid

**Comment by davidhedlund** [comment]
[mylabel:invalid](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Ainvalid%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by chatziko** [comment]
This is due to IP-based geolocation. Location Guard is meant to protect the accurate location provided via javascript, not the coarse location obtained by the IP. There is a [related point](https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard) in the FAQ.

**Comment by davidhedlund** [comment]
@chatziko Thanks.
