### ISSUE TITLE
Feature: Set the location to the same country as browsed server IP

### ISSUE THREAD

**Issue by davidhedlund** [chatziko/location-guard#20]
A good idea to always be able to browse websites that require you to be located in the same country as "they" are would be to:

1: Look up the IP of the server.
2: Look up the corresponding country for the IP.
3: Set location at a random place in that country.

**Comment by davidhedlund** [comment]
mylabel:enhancement

**Comment by davidhedlund** [comment]
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by ExE-Boss** [comment]
This however wouldn’t necessarily work, as you also need something to obfuscate your own IP address (such as [Tor](https://www.torproject.org/)), because the server can and will still use [IP address](https://www.iplocation.net/) to [country lookup](http://www.tracemyip.org/) to figure out if you are actually in the same country, because the [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) requires it.

**Comment by chatziko** [comment]
Hello and thanks for your suggestion.

This sounds good in theory but cannot be implemented for two reasons:
- finding out the server's country cannot be done reliably. Nowdays most sites use CDNs, cloud servers, etc.
- your country is revealed anyway via IP-based geolocation, Location Guard is [not meant to prevent this](https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard).
