### ISSUE TITLE
Icon not appearing after install (firefox 59)

### ISSUE THREAD

**Issue by yashanshu** [chatziko/location-guard#33]
tried installing multiple times.

**Comment by chatziko** [comment]
Try visiting https://html5demos.com/geo/. Does the icon appear after the page is loaded?

On Firefox the icon appears **only when a page asks for your location**. This is by design, so that you're not distracted by the icon for pages that don't ask for your location, and so that you easily know when a location request is made.

**Comment by chatziko** [comment]
I'm closing this issue cause it refers to an old Firefox version. Feel free to reopen if the problem remains with the latest version of both Firefox and Location Guard.
