### ISSUE TITLE
Firefox extension removed from addons.mozilla.org

### ISSUE THREAD

**Issue by baptx** [chatziko/location-guard#40]
Does anybody know why Firefox extension has been removed from addons.mozilla.org?
The download link https://addons.mozilla.org/en-US/firefox/addon/location-guard/ is not working anymore, can you fix the problem?
The addon is still installed on my latest Firefox version and it works great.

**Comment by chatziko** [comment]
Thanks for reporting! It was removed by Mozilla due to the use of an old jquery version. I uploaded a new version and it passed the initial checks, the download link now works! (I hope it stays on after Mozilla reviews it).

Location Guard doesn't appear in the search results of addons.mozilla.org though, I guess the search engine takes some time to be updated. It's also annoying that another extension named "Change Geolocation (location Guard)" tried to hijack the name.

As always, a good rating would help getting the addon back to shape :smile:

**Comment by baptx** [comment]
Thanks for the information. By the way, why not use pure JavaScript instead of jQuery? It would avoid relying on a deprecated library version and have security vulnerabilities introduced by the library. I also guess it is better for contributions to use pure JavaScript that all developers are familiar with instead of relying on a third-party library.

**Comment by chatziko** [comment]
I just use jquery ui (back in the day it was popular) for the interface (options page, demo page, etc). It's much easier than doing it from scratch.
