### ISSUE TITLE
On ipleak.net not working (anymore)

### ISSUE THREAD

**Issue by rindertb** [chatziko/location-guard#47]
Location Guard doesn't get activated anymore when pressing 'Geolocation detection' on ipleak.net. Used to work fine. No problem on other sites, though.

**Comment by KrautHolg** [comment]
Same problem here.  Firefox Quantum 66.0.3 (64-bit), Windows 10 Home Version 1809 (Build 17763.437)

**Comment by KingJohn2** [comment]
Same here, its driving me nuts, i keep thinking this addon is not working

is there any support around here?

**Comment by NormG1** [comment]
I have exactly the same problem and Web sites are seeing my real location, and giving me local businesses and in the local currency. Jow can we alert the developer that his app is broken?

**Comment by KingJohn2** [comment]
you cant, no more suppost

    On Wednesday, 29 May 2019, 22:20:58 CEST, NormG1 <notifications@github.com> wrote:  
 
 
I have exactly the same problem and Web sites are seeing my real location, and giving me local businesses and in the local currency. Jow can we alert the developer that his app is broken?

**Comment by chatziko** [comment]
I found the problem, ipleak.net uses a [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy) that prevents inline scripts from running. Location guard uses an inline script to intersept the API call, but the script is blocked by the CSP. This only happen in Firefox, Chrome allows scripts inserted by extensions even if a CSP is used.

I found a workaround, Location Guard 2.4.0 now works on ipleak.net (make sure to upgrade).

I'm closing this, feel free to reopen if it still doesn't work for you.

**Comment by NormG1** [comment]
Thanks for the great support. I could not live overseas and getAmerican TV without LG. And it has no competi,tion and it works! Perfectly.You should charge for this app. People like me who need it would gladly pay $20-25 for a one time perpetual license. -- Notm Gilbert On 21 September 2019 at 8:44:13 AM, Kostas Chatzikokolakis (notifications@github.com) wrote: 





Closed #47.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

<![CDATA[
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chatziko/location-guard/issues/47?email_source=notifications\u0026email_token=AEUEUDL54V47BM7NMSLPQ3TQKW7D3A5CNFSM4HI6N2J2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTYI5L3Y#event-2651969007",
"url": "https://github.com/chatziko/location-guard/issues/47?email_source=notifications\u0026email_token=AEUEUDL54V47BM7NMSLPQ3TQKW7D3A5CNFSM4HI6N2J2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTYI5L3Y#event-2651969007",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
]]>

**Comment by NormG1** [comment]
Btw someone ripped off your code and has an add-on called Change Geolocation (Location Guard) on the Firefox Add-On store. And he is asking for donations. If he stole any part of your code without permission you might want to have your lawyer send him a letter. -- Notm Gilbert On 21 September 2019 at 8:44:13 AM, Kostas Chatzikokolakis (notifications@github.com) wrote: 





Closed #47.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

<![CDATA[
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chatziko/location-guard/issues/47?email_source=notifications\u0026email_token=AEUEUDL54V47BM7NMSLPQ3TQKW7D3A5CNFSM4HI6N2J2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTYI5L3Y#event-2651969007",
"url": "https://github.com/chatziko/location-guard/issues/47?email_source=notifications\u0026email_token=AEUEUDL54V47BM7NMSLPQ3TQKW7D3A5CNFSM4HI6N2J2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTYI5L3Y#event-2651969007",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
]]>

**Comment by chatziko** [comment]
Thanks for the kind words.

I know about the rip-off, I don't think they stole code (which is open source anyway), but having "location guard" in the name makes no sense other than an attempt to mislead users (not that location guard is a serious brand name, but it has been mentioned in the press a few times).

If you feel like reporting this to google / mozilla be my guest (I have).

**Comment by NormG1** [comment]
Your app was missing for a few days so his was the only one.I thought you’d re-branded.I will report him -- Notm Gilbert On 22 September 2019 at 2:55:57 PM, Kostas Chatzikokolakis (notifications@github.com) wrote: 





Thanks for the kind words.
I know about the rip-off, I don't think they stole code (which
is open source anyway), but having "location guard" in the name
makes no sense other than an attempt to mislead users (not that
location guard is a serious brand name, but it has been mentioned
in the press a few times).
If you feel like reporting this to google / mozilla be my guest
(I have).
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

<![CDATA[
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chatziko/location-guard/issues/47?email_source=notifications\u0026email_token=AEUEUDJUEVTZQJJYD62OCITQK5TN3A5CNFSM4HI6N2J2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7JFXGY#issuecomment-533879707",
"url": "https://github.com/chatziko/location-guard/issues/47?email_source=notifications\u0026email_token=AEUEUDJUEVTZQJJYD62OCITQK5TN3A5CNFSM4HI6N2J2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7JFXGY#issuecomment-533879707",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
]]>
