### ISSUE TITLE
Location Guard causes CSP Violation Reports

### ISSUE THREAD

**Issue by itay-grudev** [chatziko/location-guard#64]
**Describe the bug**
Location Guard causes a CSP Violation Report on every page I visit that uses a Content Security Policy. Furthermore browsers will tend to block it, but also this bug may reveal the existence of the add-on on websites.

This may or may not be related to #47.

If applicable, add __screenshots__ to help explain your problem.
![image](https://user-images.githubusercontent.com/2123767/88693429-2dac7d80-d0f7-11ea-89b2-3704f044104c.png)

**Please complete the following information:**
 - OS: GNU/Linux
 - Browser Firefox
 - Version 78.0.2 through Snap on Ubuntu

**Comment by chatziko** [comment]
Location Guard tries to inject code directly into the page (`<script> code </script>`), so that it runs as early as possible. Even if this fails, it will try again to add a `<script src="...">` tag, which is more likely to be allowed.

These will necessarily cause CSP errors, I see no way to avoid them. Let me know if you have any idea.
